"""Simple UI localization helpers for WinWhisperPlus."""

from __future__ import annotations

from config.settings import LANGUAGES, Settings

UI_LANGUAGES = {
    "de": "Deutsch",
    "pl": "Polski",
    "en": "English",
}

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "de": {
        "app_name": "WinWhisperPlus",
        "app_title_initializing": "WinWhisperPlus - Initialisierung",
        "initializing": "Initialisierung",
        "ready": "Bereit",
        "recording": "Aufnahme läuft",
        "processing": "Verarbeitung läuft",
        "inserted": "Text eingefügt",
        "record_start": "Aufnahme starten",
        "record_stop": "Aufnahme stoppen",
        "history": "Verlauf…",
        "statistics": "Statistiken…",
        "settings": "Einstellungen…",
        "quit": "Beenden",
        "hotkey_label": "{hotkey}",
        "loading_models": "Modelle laden... ({count})",
        "loading_models_generic": "Modelle laden...",
        "loading_app": "Anwendung wird initialisiert...",
        "loading_model_kind": "Lade {model_kind}-Modell ({model_name})...",
        "model_load_failed": "Modell konnte nicht geladen werden",
        "transcription_failed": "Transkription fehlgeschlagen. Siehe Logdatei.",
        "language_message": "Sprache: {language}",
        "ui_language_message": "Oberfläche: {language}",
        "settings_title": "WinWhisperPlus - Einstellungen",
        "group_hotkeys": "Hotkeys",
        "tooltip_press_hotkey": "Klicken und gewünschte Tastenkombination drücken",
        "hotkey_record": "Aufnahme starten/stoppen:",
        "hotkey_language": "Sprache umschalten:",
        "group_language": "Diktiersprache",
        "group_ui_language": "Oberflächensprache",
        "group_microphone": "Mikrofon",
        "refresh_devices": "Geräteliste aktualisieren",
        "microphone_default": "System-Standard",
        "group_models": "Whisper-Modelle",
        "live_model": "Live (schnell):",
        "final_model": "Final (genau):",
        "model_note": "Live: tiny/base empfohlen ohne NVIDIA GPU",
        "auto_insert": "Text automatisch einfügen (Ctrl+V)",
        "live_transcription": "Laufende Erkennung und laufendes Einfügen aktivieren",
        "live_transcription_tooltip": "Während der Aufnahme werden stabile Zwischenstände laufend eingefügt.",
        "emoji_mode": "Emoji-Modus (Text mit passenden Emojis anreichern 🎉)",
        "emoji_mode_tooltip": "Bekannte Schlüsselwörter im transkribierten Text werden mit passenden Emojis ergänzt.",
        "version_label": "Version: {version}",
        "save": "Speichern",
        "cancel": "Abbrechen",
        "history_title": "Transkriptions-Verlauf",
        "history_header": "Zuletzt erkannte Texte:",
        "insert": "Einfügen",
        "close": "Schließen",
        "statistics_title": "Aufnahme-Statistik",
        "statistics_header": "Statistik: erfolgreiche finale Transkriptionen",
        "per_day": "Pro Tag",
        "per_week": "Pro Woche (Mo-So)",
        "per_month": "Pro Monat",
        "day": "Tag",
        "week": "Woche",
        "month": "Monat",
        "starts": "Anzahl Starts",
        "total": "Gesamt",
        "average": "Durchschnitt",
        "model_kind_live": "Live",
        "model_kind_final": "Final",
        "language_name_de": "Deutsch",
        "language_name_pl": "Polski",
        "language_name_en": "English",
    },
    "pl": {
        "app_name": "WinWhisperPlus",
        "app_title_initializing": "WinWhisperPlus - Inicjalizacja",
        "initializing": "Inicjalizacja",
        "ready": "Gotowe",
        "recording": "Nagrywanie trwa",
        "processing": "Przetwarzanie trwa",
        "inserted": "Tekst wstawiony",
        "record_start": "Rozpocznij nagrywanie",
        "record_stop": "Zatrzymaj nagrywanie",
        "history": "Historia…",
        "statistics": "Statystyki…",
        "settings": "Ustawienia…",
        "quit": "Zakończ",
        "hotkey_label": "{hotkey}",
        "loading_models": "Ładowanie modeli... ({count})",
        "loading_models_generic": "Ładowanie modeli...",
        "loading_app": "Inicjalizacja aplikacji...",
        "loading_model_kind": "Ładowanie modelu {model_kind} ({model_name})...",
        "model_load_failed": "Nie udało się załadować modelu",
        "transcription_failed": "Transkrypcja nie powiodła się. Sprawdź plik logu.",
        "language_message": "Język: {language}",
        "ui_language_message": "Interfejs: {language}",
        "settings_title": "WinWhisperPlus - Ustawienia",
        "group_hotkeys": "Skróty klawiszowe",
        "tooltip_press_hotkey": "Kliknij i naciśnij wybraną kombinację klawiszy",
        "hotkey_record": "Start/stop nagrywania:",
        "hotkey_language": "Przełącz język:",
        "group_language": "Język dyktowania",
        "group_ui_language": "Język interfejsu",
        "group_microphone": "Mikrofon",
        "refresh_devices": "Odśwież listę urządzeń",
        "microphone_default": "Domyślny systemowy",
        "group_models": "Modele Whisper",
        "live_model": "Live (szybki):",
        "final_model": "Final (dokładny):",
        "model_note": "Dla trybu live bez GPU NVIDIA zalecane są tiny/base",
        "auto_insert": "Wstawiaj tekst automatycznie (Ctrl+V)",
        "live_transcription": "Włącz transkrypcję i wstawianie na żywo",
        "live_transcription_tooltip": "Podczas nagrywania stabilne fragmenty są wstawiane na bieżąco.",
        "emoji_mode": "Tryb emoji (wzbogacaj tekst pasującymi emoji 🎉)",
        "emoji_mode_tooltip": "Znane słowa kluczowe w transkrypcji są uzupełniane odpowiednimi emoji.",
        "version_label": "Wersja: {version}",
        "save": "Zapisz",
        "cancel": "Anuluj",
        "history_title": "Historia transkrypcji",
        "history_header": "Ostatnio rozpoznane teksty:",
        "insert": "Wstaw",
        "close": "Zamknij",
        "statistics_title": "Statystyki nagrań",
        "statistics_header": "Statystyki: udane końcowe transkrypcje",
        "per_day": "Na dzień",
        "per_week": "Na tydzień (pon.-niedz.)",
        "per_month": "Na miesiąc",
        "day": "Dzień",
        "week": "Tydzień",
        "month": "Miesiąc",
        "starts": "Liczba uruchomień",
        "total": "Łącznie",
        "average": "Średnio",
        "model_kind_live": "live",
        "model_kind_final": "final",
        "language_name_de": "Niemiecki",
        "language_name_pl": "Polski",
        "language_name_en": "Angielski",
    },
    "en": {
        "app_name": "WinWhisperPlus",
        "app_title_initializing": "WinWhisperPlus - Initializing",
        "initializing": "Initializing",
        "ready": "Ready",
        "recording": "Recording",
        "processing": "Processing",
        "inserted": "Text inserted",
        "record_start": "Start recording",
        "record_stop": "Stop recording",
        "history": "History…",
        "statistics": "Statistics…",
        "settings": "Settings…",
        "quit": "Quit",
        "hotkey_label": "{hotkey}",
        "loading_models": "Loading models... ({count})",
        "loading_models_generic": "Loading models...",
        "loading_app": "Initializing application...",
        "loading_model_kind": "Loading {model_kind} model ({model_name})...",
        "model_load_failed": "Could not load model",
        "transcription_failed": "Transcription failed. See log file.",
        "language_message": "Language: {language}",
        "ui_language_message": "Interface: {language}",
        "settings_title": "WinWhisperPlus - Settings",
        "group_hotkeys": "Hotkeys",
        "tooltip_press_hotkey": "Click and press the desired key combination",
        "hotkey_record": "Start/stop recording:",
        "hotkey_language": "Cycle language:",
        "group_language": "Dictation language",
        "group_ui_language": "Interface language",
        "group_microphone": "Microphone",
        "refresh_devices": "Refresh device list",
        "microphone_default": "System default",
        "group_models": "Whisper models",
        "live_model": "Live (fast):",
        "final_model": "Final (accurate):",
        "model_note": "For live mode without an NVIDIA GPU, tiny/base are recommended",
        "auto_insert": "Automatically insert text (Ctrl+V)",
        "live_transcription": "Enable live recognition and live insertion",
        "live_transcription_tooltip": "Stable partial results are inserted continuously while recording.",
        "emoji_mode": "Emoji mode (enrich text with matching emojis 🎉)",
        "emoji_mode_tooltip": "Known keywords in the transcription are supplemented with matching emojis.",
        "version_label": "Version: {version}",
        "save": "Save",
        "cancel": "Cancel",
        "history_title": "Transcription history",
        "history_header": "Recently recognized texts:",
        "insert": "Insert",
        "close": "Close",
        "statistics_title": "Recording statistics",
        "statistics_header": "Statistics: successful final transcriptions",
        "per_day": "Per day",
        "per_week": "Per week (Mon-Sun)",
        "per_month": "Per month",
        "day": "Day",
        "week": "Week",
        "month": "Month",
        "starts": "Starts",
        "total": "Total",
        "average": "Average",
        "model_kind_live": "live",
        "model_kind_final": "final",
        "language_name_de": "German",
        "language_name_pl": "Polish",
        "language_name_en": "English",
    },
}


def get_ui_language(settings: Settings | None) -> str:
    """Return a valid UI language code."""
    if settings is None:
        return "de"
    language = getattr(settings, "ui_language", "de")
    return language if language in UI_LANGUAGES else "de"


def tr(key: str, settings: Settings | None = None, **kwargs) -> str:
    """Translate *key* for the configured UI language."""
    language = get_ui_language(settings)
    value = _TRANSLATIONS.get(language, {}).get(key)
    if value is None:
        value = _TRANSLATIONS["de"].get(key, key)
    return value.format(**kwargs) if kwargs else value


def localized_spoken_language_name(language_code: str, settings: Settings | None = None) -> str:
    """Return the display name of a dictation language in the current UI language."""
    key = f"language_name_{language_code}"
    translated = tr(key, settings)
    if translated == key:
        return LANGUAGES.get(language_code, language_code)
    return translated
